services:
  mongodb:
    image: mongo:6.0
    container_name: mongo_bun_app
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
      MONGO_INITDB_DATABASE: appdb
    ports:
      - "27020:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
